### ISSUE TITLE
document how various relations are stored

### ISSUE THREAD

**Issue by SimonHeimberg** [DATA-DOG/DataDogAuditBundle#38]
There is no documentation how various relations are stored.

Please write documentation about this.
Or **even better** write the OneToMany associations handier. (Doing database queries for a json string is unhandy and not precise. Even finding the fk requires this hack.)

What I found out:

ManyToMany association, owning side:
 ```yaml
AuditLog (of owning side entity):
    action: 'associate' #
    source:
        # -> points to Association
        id: # internal id of this association
        typ: # type (similar to bundle+class) of associated entity
        tbl: # table where the entity of this association is stored
        label: # value of associated entity, as string
        fk: # id of the associated entity
        class: # class of associated entity
    target:
        # -> points to Association
        class: class of related association
        tbl: table of ...
        fk: id of related association
    diff: []
        # empty array
```
ManyToMany association, other side:
`#nothing`

OneToMany association, owning side:
 ```yaml
AuditLog (of owning side entity):
    action: 'update' # or insert
    source:
        # -> points to Association
        fk: id of this audit log
    target:
        null
    diff: # as json
        ...
        associationProperyName:
            old:
                typ: # see in ManyToMany 
                tbl: # see in ManyToMany 
                label: # see in ManyToMany 
                fk: # id of the associated entity
                class: # see in ManyToMany 
            new:
                typ: # see in ManyToMany
                ...
            col: # column name
```
