### ISSUE TITLE
Defining custom labeler breaks audited entities config

### ISSUE THREAD

**Issue by curtchan** [DATA-DOG/DataDogAuditBundle#58]
As in subject.

Example on defining labeler (as from docs):

```
    datadog.event_subscriber.audit:
        class: 'DataDog\AuditBundle\EventSubscriber\AuditSubscriber'
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_subscriber, connection: default }
        calls:
            - ['setLabeler', [['\AppBundle\Labeler\AuditLabeler', 'getLabel']]]
```
debug:config sees config okay
dump inside isEntityUnaudited proves the array of unaudited entities is empty.

**Comment by curtchan** [comment]
Quick fix is to define call manually, but it definitely needs to be worked on.
```

    datadog.event_subscriber.audit:
        class: 'DataDog\AuditBundle\EventSubscriber\AuditSubscriber'
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_subscriber, connection: default }
        calls:
            - ['setLabeler', [['\AppBundle\Labeler\AuditLabeler', 'getLabel']]]
            - ['addAuditedEntities', [['AppBundle\Entity\Reservation', 'AppBundle\Entity\Tariff', 'AppBundle\Entity\Parking', 'AppBundle\Entity\User']]]

```
